#!/usr/bin/env bash
# Script that change localhost

cp /etc/hosts /etc/hosts.bak
sed -i '/127.0.0.2 localhost/d' /etc/hosts
sed -i '/8.8.8.8 facebook.com/d' /etc/hosts
echo "/127.0.0.2 localhost" >> /etc/hosts
echo "/8.8.8.8 facebook.com" >> /etc/hosts

echo "Your IP has been changed"